package com.example.wcartvendor.models

class Constants{
    val MY_PREFS_NAME = "MyPrefsFile"
    val KEY_OTP_LOGGED_IN = "key_logged_in"
    val KEY_LOGGED_IN = "key_logged_in"
    val KEY_ONPAYMENT = "key_onpayment"
    val KEY_ONTRIP = "key_ontrip"
    val ARRIVED = "ARRIVED"
    val KEY_ONTRIP2 = "key_ontrip2"
    val REGISTER = "https://tranznexs.com/riderapi/registration"
    val EDIT_PROFILE = "https://tranznexs.com/riderapi/edit-profile"
    val user_id = "user_id"
    val firstname = "firstname"
    val lastname = "lastname"
    val email_id = "email_id"
    val password = "password"
    val address = "address"
    val state = "state"
    val city = "city"
    val image = "image"
    val mobileno = "mobileno"
    val country = "country"
    val amount = "amount"
    val payment_type = "payment_type"
    val Payment_method = "Payment_method"
    val rateperkm = "rateperkm"
    val bikeName = "bikeName"
    val distance = "distance"
    val FAV_HOME = "fav_home"
    val FAV_WORK = "fav_work"
    val FAV_OTHER = "fav_other"
    val Hourlyamount = "Hourlyamount"
}